name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Adjust to the version of .NET you are using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --output ./CI

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Prepare directory
      run: |
        if [ ! -d "PDMSystem/CI" ]; then
          mkdir -p PDMSystem/CI
        fi
        ls -la PDMSystem/CI

    - name: Copy binaries
      run: |
        cp -r ./CI/* PDMSystem/CI/
        ls -la PDMSystem/CI

    - name: Commit binaries
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add PDMSystem/CI
        git commit -m "Add build output"
        git push origin main


