name: CI
run-name: Pipeline CI runned by ${{ github.actor }} in ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: PDMSystem.sln                        
      Test_Project_Path: PDMSystem\PDMSystem.csproj                

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore Nuget Packages
      run: nuget restore PDMSystem.sln

    - name: Build the solution
      run: msbuild PDMSystem.sln /p:Configuration=Release
  
  release:
    runs-on: windows-latest
    needs: [build]

    steps:
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build-Artifacts
        path: PDMSystem/bin/Release**
